services:
  app:
  
    build: .
    ports:
      - "8000:8000"
    env_file:
    - .env  
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/events_db
      - SQS_ENDPOINT_URL=${AWS_REGION}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - LOG_LEVEL=${LOG_LEVEL}
      - WORKER_CONCURRENCY=${WORKER_CONCURRENCY}
      
    depends_on:
      - db
      - elasticmq
    volumes:
      - ./app:/app/app

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=events_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  elasticmq:
    image: softwaremill/elasticmq-native
    ports:
      - "9324:9324"
      - "9325:9325"
    volumes:
      - ./elasticmq.conf:/opt/elasticmq.conf

volumes:
  postgres_data:
  